#!/bin/bash
# to reference filename, execute command like ./watch-files [path to folder] 'wezterm imgcat $filepath'

FOLDER_TO_WATCH=${1:-$(pwd)}

inotifywait -m -e close_write -q "$FOLDER_TO_WATCH" |
while read -r directory events filename; do
    filepath="$directory$filename"
    echo "Event detected: $events on $filepath"

    eval ${2:-echo "File Change: $filepath"}
done
