#!/bin/bash

FOLDER_TO_WATCH=${1:-$(pwd)}

inotifywait -m -e close_write -q "$FOLDER_TO_WATCH" |
while read -r directory events filename; do
    echo "Event detected: $events on $directory$filename"

    ${2:-echo "File Change: $filename"}
done
