version: '3'

tasks:
  update:
    cmds:
      - sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d

  build:
    preconditions:
      - command -v podman
      - test -f Containerfile
    cmds:
      - podman build . -t dev
      - podman system prune -f

  build-arm:
    preconditions:
      - test -f Containerfile.arm.patch
    cmds:
      - git apply Containerfile.arm.patch
      - task: build
      - git checkout Containerfile

  run:
    preconditions:
      - test -n "$(podman images -q dev)"
    cmds:
      - | 
        podman run -it --name dev --network host \
        -v workspaces:/root/workspaces \
        -v persist-config:/root/persist-config \
        --replace dev bash 

  run-bg:
    preconditions:
      - test -n "$(podman images -q dev)"
    cmds:
      - | 
        podman run -d --name dev --network host \
        -v workspaces:/root/workspaces \
        -v persist-config:/root/persist-config \
        --replace dev 

  run-bg-persist:
    - task: run-bg
    - mkdir -p "$HOME/.config/systemd/user"
    - podman generate systemd dev > "$HOME/.config/systemd/user/container-dev.service"
    - systemctl --user enable container-dev.service
