AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance with basic UserData

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-069cb3204f7a90763
      SecurityGroupIds:
        - !Ref InstanceSecurityGroup
      UserData:
        Fn::Base64: !Sub |
          #!/bin/bash
          sudo apt update
          sudo apt install git curl -y
          # git clone https://github.com/Nyr/openvpn-install.git /home/ubuntu/openvpn-install

  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Enable SSH access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        # - IpProtocol: udp
        #   FromPort: 1194
        #   ToPort: 1194
        #   CidrIp: 0.0.0.0/0

  MyEIP:
    Type: AWS::EC2::EIP
    Properties:
      Domain: vpc

  MyEIPAssociation:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref MyEC2Instance
      EIP: !Ref MyEIP

Outputs:
  InstanceId:
    Description: The Instance ID
    Value: !Ref MyEC2Instance
  PublicIP:
    Description: Elastic IP address of the EC2 instance
    Value: !Ref MyEIP