---
- name: Install Neovim
  hosts: localhost
  tasks:
    - name: Install Required Packages
      ansible.builtin.dnf:
        name: "{{ item }}"
        state: present
      loop:
        - neovim
        - git
        - curl
        - nodejs
        - "@Development Tools"
      become: true
    
    - name: Install Required NPM packages
      community.general.npm:
        name: "{{ item }}"
        global: true
      loop:
        - bash-language-server
        - yaml-language-server
        - pyright
      become: true

    - name: Create folder path for nvim configs
      ansible.builtin.file:
        state: directory
        path: "{{ ansible_env.HOME }}/.config/nvim"

    - name: Copy config files
      ansible.builtin.copy:
        src: init.lua
        dest: "{{ ansible_env.HOME }}/.config/nvim/init.lua"
