main:  
  rules:
    - if: $GITLAB_BASE_IMAGE && $AWS_STS_ROLE_ARN && $AWS_STS_EXTERNAL_ID && $OPENSSL_ENC_PRE_SHARED_KEY
  image: ${GITLAB_BASE_IMAGE}
  script:
    - OUTPUT=$(aws sts assume-role --role-arn ${AWS_STS_ROLE_ARN} --external-id ${AWS_STS_EXTERNAL_ID} --role-session-name ci)
    
    - echo "$OUTPUT" | openssl enc -k ${OPENSSL_ENC_PRE_SHARED_KEY} -aes256 -base64 -pbkdf2 -e -out cipher.txt
  artifacts:
    paths:
      - cipher.txt
    expire_in: 1 hour
