# Set SSDC_USERNAME and SSDC_PASSWORD as github secrets
# Currently doesn't seem to work because of reCAPTCHA IP block: Useful as example
name: Grab SSDC Login
on:
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run bootstrap
        run: |
          wget https://raw.githubusercontent.com/cnboonhan/conf/main/bootstrap.py
          python3 bootstrap.py

      - name: Install WebDriver
        run: |
          source "$HOME/.conf/.venv/bin/activate"
          cd "$HOME/.conf" && python3 -m scripts.installation.webdriver.install-webdriver
          deactivate

      - name: Grab Credentials
        env:
          USERNAME: ${{ secrets.SSDC_USERNAME }}
          PASSWORD: ${{ secrets.SSDC_PASSWORD }}
        run: |
          source "$HOME/.conf/.venv/bin/activate"
          cd "$HOME/.conf" && python3 -m scripts.credentials-grabber.ssdc 
          openssl enc -aes-256-cbc -in /tmp/cookies.txt -out /tmp/cookies.txt.enc -k ${{ secrets.SSDC_PASSWORD }}
          echo "openssl enc -d -aes-256-cbc -in cookies.txt.enc -out cookies.txt" > /tmp/decrypt.sh
          deactivate  

      - uses: actions/upload-artifact@v3
        with:
          name: creds
          path: |
            /tmp/cookies.txt.enc
            /tmp/decrypt.sh
            /tmp/log.txt
