name: CI

on:
  push:
    branches: [ "**" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Run bootstrap
        run: |
          wget https://raw.githubusercontent.com/cnboonhan/conf/main/bootstrap.py
          python3 bootstrap.py

      - name: Install Node
        run: |
          source "$HOME/.conf/.venv/bin/activate"
          cd "$HOME/.conf" && python3 -m scripts.installation.node.install-node
          deactivate

      - name: Install Vim
        run: |
          source "$HOME/.conf/.venv/bin/activate"
          cd "$HOME/.conf" && python3 -m scripts.installation.vim.install-vim
          deactivate
